name: Transport Pre-merge pipeline

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go get ./...
      - run: go test -v -coverprofile cover.out ./...
      - run: go tool cover -func cover.out | grep total | awk '{print "total coverage "$3}'
